apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: utility
  labels:
    app: auth
    env: charite
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
      env: charite
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 33%
  template:
    metadata:
      labels:
        app: auth
        env: charite
    spec:
      containers:
        - name: authn
          image: 10.32.42.225:5000/auth:<VERSION>
          ports:
            - containerPort: 5061
          env:
          - name: env
            value: "charite"
          readinessProbe:
            tcpSocket:
              port: 5061
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              memory: "1000Mi"
              cpu: "1"
            limits:
              memory: "1000Mi"
              cpu: "1"
      nodeSelector:
        namespace: utility
---
apiVersion: v1
kind: Service
metadata:
  name: auth
  namespace: utility
  labels:
    app: auth
    env: charite
spec:
  ports:
  - name: http
    port: 5061
    targetPort: 5061
  selector:
    app: auth
    env: charite
  type: ClusterIP
